{
 "title": "Service Level Objectives (Service Detail)",
 "tags": [ "SLO" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SLO_domain",
    "label": "Domain",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total,slo_domain)"
    }
   },
   {
    "name": "SLO_app",
    "label": "Service",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\"},slo_app)"
    }
   },
   {
    "name": "SLO_type",
    "label": "SLO Type",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\", slo_app=\"${SLO_app}\"},slo_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${SLO_app}: ${SLO_type}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "SLO_type" },
  {
   "title": "5m Error Budget [events]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[5m]))\n* (1 - (sum(service_level_objective:class + on(slo_class) (0* job:slo_errors_per_request:ratio_rate5m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})) / 100))"
    }
   ]
  },
  {
   "title": "5m Fail Count [events]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{result=\"fail\",slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[5m]))"
    }
   ]
  },
  {
   "title": "5m Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "(1 - job:slo_errors_per_request:ratio_rate5m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}) *100",
     "legendFormat": "Success Ratio"
    },
    {
     "expr": "service_level_objective:class + on(slo_class) (0* job:slo_errors_per_request:ratio_rate5m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})",
     "legendFormat": "Service Level Objective"
    }
   ]
  },
  {
   "title": "30m Error Budget [events]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[30m]))\n* (1 - (sum(service_level_objective:class + on(slo_class) (0* job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})) / 100))"
    }
   ]
  },
  {
   "title": "30m Fail Count [events]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{result=\"fail\",slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[30m]))"
    }
   ]
  },
  {
   "title": "30m Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "(1 - job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}) *100",
     "legendFormat": "Success Ratio"
    },
    {
     "expr": "service_level_objective:class + on(slo_class) (0* job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})",
     "legendFormat": "Service Level Objective"
    }
   ]
  },
  {
   "title": "5m Burn Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{result=\"fail\",slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[5m])) / (\n  sum(increase(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[5m])) * (\n    1 - (sum(service_level_objective:class + on(slo_class)\n    (0* job:slo_errors_per_request:ratio_rate5m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})) / 100)\n  )\n)"
    }
   ]
  },
  {
   "title": "30m Burn Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(slo_domain_slo_class_slo_app:slo_events_total{result=\"fail\",slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[30m])) / (\n  sum(increase(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"}[30m])) * (\n    1 - (sum(service_level_objective:class + on(slo_class)\n    (0* job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\",slo_app=\"${SLO_app}\",slo_type=\"${SLO_type}\"})) / 100)\n  )\n)"
    }
   ]
  }
 ]
}