{
 "title": "Service Level Objectives (Class Overview)",
 "tags": [ "SLO" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "SLO_domain",
    "label": "Domain",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total,slo_domain)"
    }
   },
   {
    "name": "SLO_class",
    "label": "SLO Class",
    "query": {
     "query": "label_values(slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\"},slo_class)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SLI Success Overview",
   "type": "table",
   "description": "Percentage of successful SLI events to all events.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\", slo_class=~\"${SLO_class}\"}) *100"
    }
   ]
  },
  {
   "title": "SLO Class Overview",
   "type": "piechart",
   "description": "Number of services in each SLO class in given domain.",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(slo_class) (count (slo_domain_slo_class_slo_app:slo_events_total{slo_domain=\"${SLO_domain}\"}) by(slo_app,slo_class))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI Success Overview",
   "type": "timeseries",
   "description": "Percentage of successful SLI events to all events.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - job:slo_errors_per_request:ratio_rate30m{slo_domain=\"${SLO_domain}\", slo_class=~\"${SLO_class}\"}) *100",
     "legendFormat": "{{slo_app}}, {{slo_type}}"
    }
   ]
  },
  {
   "title": "SLO Overview",
   "type": "table",
   "description": "Overview of Service Level Objectives per SLO class",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "targets": [
    { "expr": "service_level_objective:class" }
   ]
  }
 ]
}